// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoErrorBlazor.DAL;

namespace ProyectoErrorBlazor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200527190424_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("ProyectoErrorBlazor.Models.Errores", b =>
                {
                    b.Property<int>("errorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("hallazgo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("importancia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ruta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("errorId");

                    b.ToTable("Errores");
                });
#pragma warning restore 612, 618
        }
    }
}
